language: python

python: 3.6

dist: bionic

services:
    - docker

addons:
    chrome: stable

cache:
    - pip
    - npm
    - yarn

before_install:
    - |
      if [ "$SKIP_SERVER_INSTALL" != "true" ]; then
        docker-compose -f .travis-docker-compose.yml up -d
      fi

install:
    - |
      if [ "$SKIP_SERVER_REQUIREMENTS_INSTALL" != "true" ]; then
        pip install -r requirements.txt
      fi
    - |
      if [ "$SKIP_SERVER_REQUIREMENTS_INSTALL" != "true" ]; then
        pip install -r dev-requirements.txt
      fi
    - |
      if [ "$SKIP_CLIENT_REQUIREMENTS_INSTALL" != "true" ]; then
        yarn install
      fi

jobs:
    include:
        - script: flake8
          name: "flake8"
          env: SKIP_SERVER_INSTALL=true SKIP_CLIENT_REQUIREMENTS_INSTALL=true
        - script: pytest --disable-pytest-warnings --cov=newsroom
          name: "pytest"
          env: SKIP_CLIENT_REQUIREMENTS_INSTALL=true
        - script: behave --format progress2 --logging-level=ERROR
          name: "behave"
          env: SKIP_CLIENT_REQUIREMENTS_INSTALL=true
        - script: npm run lint
          name: "lint"
          env: SKIP_SERVER_INSTALL=true SKIP_SERVER_REQUIREMENTS_INSTALL=true
        - script: npm run test
          name: "karma"
          env: SKIP_SERVER_INSTALL=true SKIP_SERVER_REQUIREMENTS_INSTALL=true
        - script: npm run build
          name: "build"
          env: SKIP_SERVER_INSTALL=true SKIP_SERVER_REQUIREMENTS_INSTALL=true
