language: python

python: 3.6

dist: bionic

services:
    - docker

addons:
    chrome: stable

cache:
  - pip
  - npm
  - yarn

before_install:
    - docker-compose -f .travis-docker-compose.yml up -d

install:
    - pip install -r requirements.txt
    - pip install -r dev-requirements.txt
    - yarn install

script:
    - flake8
    - pytest --disable-pytest-warnings --cov=newsroom
    - npm run lint
    - npm run test
    - npm run build
    - behave --format progress2 --logging-level=ERROR
